export const GAASSET_LIST_REQUEST = "GAASSET_LIST_REQUEST";
export const GAASSET_LIST_SUCCESS = "GAASSET_LIST_SUCCESS";
export const GAASSET_LIST_FAIL = "GAASSET_LIST_FAIL";

export const GAASSET_DETAILS_REQUEST = "GAASSET_DETAILS_REQUEST";
export const GAASSET_DETAILS_SUCCESS = "GAASSET_DETAILS_SUCCESS";
export const GAASSET_DETAILS_FAIL = "GAASSET_DETAILS_FAIL";

